### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by IvanPanchak** [strange-v/power-outage-schedule-card#2]
Good afternoon, can you add step-by-step instructions for beginners, Thank you!

**Comment by strange-v** [comment]
1. Install HACS.
2. Go to HACS -> Frontend -> Custom repositories (in the menu).
3. Set the repository to `https://github.com/strange-v/power-outage-schedule-card` and the category to `Lovelace`.
4. Click Explore & download repositories and search for `power outage schedule card`.
5. Select the card and click download.
6. HA restart might be required.
7. Configure the sensors using [Data retrieval example](https://github.com/strange-v/power-outage-schedule-card?tab=readme-ov-file#data-retrieval-example) (add the code into configuration.yaml of the HA).
8. Configure the card using [Card configuration example](https://github.com/strange-v/power-outage-schedule-card?tab=readme-ov-file#card-configuration-example) (the card cannot be configured in the UI mode, only in code).

I doubt I'll be creating something more detailed. Please, ask here if some steps are not clear.

**Comment by strange-v** [comment]
A basic how-to has been added.
