### ISSUE TITLE
Data provider changed response format

### ISSUE THREAD

**Issue by yurkiv** [strange-v/power-outage-schedule-card#4]
Since 2024-08-20 hour object was changed to
```
{
    "hour": "0-1",
    "electricity": 0,
    "description": "00:00-01:00",
    "periodLimitValue": 1
}
```
So, we have to use `periodLimitValue` to detect hour instead of `hour`.

**Comment by strange-v** [comment]
Thanks. Yesterday, I had a fake fully green chart due to this.
The change will be reflected in the docs.
